// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID                string `json:"id"`
	Modal             string `json:"modal"`
	Caridentifier     string `json:"caridentifier"`
	Dateofmanufacture string `json:"dateofmanufacture"`
	Totalcar          int    `json:"totalcar"`
	Totalinuse        int    `json:"totalinuse"`
}

type Login struct {
	Mobilenumber string `json:"mobilenumber"`
	Password     string `json:"password"`
}

type NewCar struct {
	Modal             string `json:"modal"`
	Dateofmanufacture string `json:"dateofmanufacture"`
	Caridentifier     string `json:"caridentifier"`
	Totalcar          int    `json:"totalcar"`
	Totalinuse        int    `json:"totalinuse"`
}

type NewUser struct {
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	Mobilenumber string `json:"mobilenumber"`
	Password     string `json:"password"`
}

type ProcessCar struct {
	Caridentifier string `json:"caridentifier"`
	Bookedtill    string `json:"bookedtill"`
}

type User struct {
	ID           string `json:"id"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	Mobilenumber string `json:"mobilenumber"`
	Passkey      string `json:"passkey"`
}
