CREATE TABLE IF NOT EXISTS Users(
    ID SERIAL PRIMARY KEY,
    Firstname VARCHAR (127) NULL,
    Lastname VARCHAR (127) NULL,
    Mobilenumber VARCHAR (127) NOT NULL UNIQUE,
    Passkey VARCHAR (127) NOT NULL UNIQUE,
    Token VARCHAR (255) NULL
)